### ISSUE TITLE
Implement 02-client-refactor

### ISSUE THREAD

**Issue by seunlanlege** [ComposableFi/yui-ibc-solidity#1]
Currently the solidity implementation still uses the outdated `CheckHeaderAndUpdateState` methods for the client. This should be split into four methods so it mimics our api in ibc-rs:

https://github.com/ComposableFi/ibc-rs/blob/9925f24c5061832ec5d5a0f4b16a1802dbb75128/modules/src/core/ics02_client/client_def.rs#L38-L66

This api refactor enables the beefy v1 light client to exist.

**Comment by nadeemb53** [comment]
Implemented in [#115](https://github.com/hyperledger-labs/yui-ibc-solidity/pull/115)
